name: Data Preprocessing Automation

on:
  push:
    branches:
      - main

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Pandas
      run: pip install pandas

    - name: Run Automation Script
      run: |
        cd preprocessing
        python automate_AsmaulHusna.py

    - name: Upload Preprocessed Data Artifact
      uses: actions/upload-artifact@v3
      with:
        name: preprocessed-dataset
        path: preprocessing/getcontact_preprocessing.csv